---
title: "oc_validVac"
author: "Beth Savagar"
date: "2023-11-13"
output: html_document
---

# APPLIED EXAMPLES LHS - PRELIMINARY ANALYSIS 
- Run model for valid pars

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
# libraries not accounted for in setup script
library(GGally)
plotsave <- F
custom_theme <- theme_bw() + theme(text = element_text(family = "Times New Roman", size = 9))
theme_set(custom_theme)
```

```{r modSetup1}
############
## SETUP ##
############
local <- T
# local filepath: 
if(local){
  filepath <- ""
}else{
  # cluster filepath
  filepath <- "/storage/users/bsavagar/"
}

## Libraries
source(paste0(filepath,"scripts/setup.R")) 

## Functions:
source(paste0(filepath, "functions/Appliedfunc.R")) # wrapper function
source(paste0(filepath, "functions/demos_summary.R")) # summary stats for output
source(paste0(filepath, "functions/dynmod-vac.R")) # flock dynamics model function
source(paste0(filepath, "functions/output.R")) # what to include in output df
source(paste0(filepath, "functions/GSA_outputs.R")) # summary stats accounting for vac

```


```{r selectData}
# 9/11/23: Run model with LHS of oc parameter space. Analyse results against original valid population conditions and against oc population growth reports. 

applied_example <- T

## Load parameters
datafile <- "-oc_validPars"
fix_age_data_full <- read_csv(paste0("data/Applied_parameters/state_vars",datafile,".csv"),col_names=T)
var_demo_data_full <- read_csv(paste0("output/Applied/applied_outValidPars_OC_2023-12-05.csv"))
imm_decay_corrected <- read_csv("data/imm_decay_bodjo_v2.csv") 

## Datasets
datasets <- fix_age_data_full %>% select(-parameter) %>% colnames()
```

```{r modSetup2}

######################
## MODEL SETUP ##
######################

## Simulation:
TimeStop_dynamics <- 20*52 # 2 years only interested in rates for 1 y
TimeStop_transmission <- 24 # 1 day, hourly timestep for transmission component
min_pop <- 1 # set minimum size of population, if pop drops below then set to 0

#######################
## Vaccination Setup ##
#######################
# see applied_vaccination
pV <- 1
source("scripts/applied/applied_vaccination.R")
Vstart <- Vprog %>% filter(Vround==1) %>% pull(Vweek)

##################
## RUN MODEL ##
##################

turnover <- F; 
dynamics <- T; 
transmission <- F; 
clean_environment <- T

# timepoints for population growth
t2 <- TimeStop_dynamics/2 # 5 year pop growth
t1 <- TimeStop_dynamics


##################################
## LHS SETUP  ##
##################################

lhs <- F
lhs_n <- 0 # number of sets (parameter combinations)
pairs_plot <- F
SA <- F

```


```{r loopDynamics}

###################
## MODEL OUTPUT ##
###################

## Model Output
output <- "dynamics" # Output options: "summary" (stats with age-group prop), "summary_all" (stats with age-sex group prop), "dynamics" (pop metrics over time)
# create empty dataframe to store output
summary_df <- output_func(TimeStop_dynamics, output) 

# validOut = list to store outputs
GSAoutput <- c(); 
ocOut.dynamics <- list()

#####################
## PARALLELISATION ##
#####################

print("start-parallel")

## Local parallelisation
if(local){
  cores=detectCores()
  cl <- makeCluster(cores[1]-1)
  registerDoParallel(cl)
}else{
  cores=detectCores()
  cl <- makeCluster(10)
  registerDoParallel(cl)
}
print("parallel-verified")
print("start-model")


#####################
## LOOP ##
#####################

dataset <- datasets

if (dataset == "lesnoff.ft") {
  rates <- "wkly"
} else{
  rates <- "yrly"
}

fixdata <- dataset # set dataset for state_vars
vardata <- dataset
  
if(lhs){
  source("scripts/applied/applied_lhs.R") # output var_input_df contains all parameter combinations for uncertain demographics.
}

profOrder <- var_demo_data_full %>% select(prof) %>% pull()
var_input_backup <- var_demo_data_full %>% select(-prof)
  
  ################
  ## SIMULATION ##
  ################
  Out.dynamics <- foreach (i = 1:nrow(var_input_backup),
                                .packages = c("dplyr", "tibble")) %dopar% {
                                  print(i)
                                  
                                  var_input_full <- unlist(var_input_backup[i, ])
                                  
                                  App_func(
                                    imm_decay_corrected,
                                    var_input_full,
                                    fix_age_data_full,
                                    f_list,# initial state of female population
                                    m_list, # initial state of male population
                                    TimeStop_dynamics,# 1 year, weekly timestep for demographic component
                                    TimeStop_transmission, # 1 day, hourly timestep for transission component
                                    output,# model output: tracker or summary stats
                                    summary_df, #
                                    clean_environment,
                                    Vstart,
                                    Vprog,
                                    fixdata,
                                    vardata
                                  )
                                }
  
stopCluster(cl)

```


```{r analysisDynamics}


custom_palette <- c("#004D40", "#00695C", "#00796B", "#00897B", "#009688", "#4A148C", "#6A1B9A", "#7B1FA2", "#8E24AA", "#9C27B0")

# ocOut.dynamics
immDynamics <- lapply(Out.dynamics, select, prop_immune) %>%
  bind_cols() %>%
  t() %>%
  as.data.frame()

colnames(immDynamics) <- 1:ncol(immDynamics)
rownames(immDynamics) <- 1:nrow(immDynamics)

immDynamics.clean <- immDynamics %>%
  select((t2):ncol(immDynamics)) %>%
  mutate(prof = profOrder)

immDynamics.long <- immDynamics.clean %>%
  gather(key = "weeks", value = "prop_immune", -prof) %>%
  mutate(weeks = as.numeric(weeks))

# Calculate mean and confidence interval
summary_data <- immDynamics.long %>%
  group_by(prof,weeks) %>%
  summarise(
    mean_value = mean(prop_immune),
    lower_ci = quantile(prop_immune, 0.025),
    upper_ci = quantile(prop_immune, 0.975)
  )

plot_immVar <- ggplot(summary_data, aes(x = weeks, y = mean_value, group = prof)) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), fill = "grey", alpha = 0.5) +
  geom_line(aes(col = prof)) +
  geom_hline(yintercept = 0.7, linetype = "dashed")+
  facet_wrap(~prof, nrow = 2)+
  labs(x="Time (weeks)", y = "Proportion Immune", col = "Profile")+
  coord_cartesian(xlim = c(500,750))+
  scale_colour_manual(values = custom_palette)


filename_immVar <- "ImmDyn100_OCvalid.png"
ggsave(paste0("plots/applied/",filename_immVar), plot = plot_immVar, width = 20, height = 10, units = "cm")

```


```{r loopSummary}
lhs_n <- 1e3
## Model Output
output <- "summary_all" # Output options: "summary" (stats with age-group prop), "summary_all" (stats with age-sex group prop), "dynamics" (pop metrics over time)
# create empty dataframe to store output
summary_df <- output_func(TimeStop_dynamics, output) 

# validOut = list to store outputs
GSAoutput <- c(); 
ocOut.sum <- list()
ocPars <- list()

#####################
## PARALLELISATION ##
#####################

print("start-parallel")

## Local parallelisation
if(local){
  cores=detectCores()
  cl <- makeCluster(cores[1]-1)
  registerDoParallel(cl)
}else{
  cores=detectCores()
  cl <- makeCluster(10)
  registerDoParallel(cl)
}
print("parallel-verified")
print("start-model")


#####################
## LOOP ##
#####################

for(d in 1:length(datasets)){
  dataset <- datasets[d]
  data_filename <- gsub("\\.","",dataset)
  
  ##################################
  ## LHS DEMOGRAPHIC PARS ##
  ##################################
  
  data_filename <- gsub("\\.", "", dataset)
  
  if (dataset == "lesnoff.ft") {
    rates <- "wkly"
  } else{
    rates <- "yrly"
  }
  
  # set seed
  set.seed(1) # so that results are consistent
  
  pars_min <- paste0(dataset, ".min") # minimum val
  pars_max <-  paste0(dataset, ".max") # maximum val
  fixdata <- dataset # set dataset for state_vars
  vardata <- dataset
  
  source("scripts/applied/applied_lhs.R") # output var_input_df contains all parameter combinations for uncertain demographics.
  
  
  # Format demographic parameter sets:
  var_input_backup <- var_input_df %>% as.data.frame()
  
  ################
  ## SIMULATION ##
  ################
  Out.summary <- foreach (i = 1:nrow(var_input_backup),
                                .packages = c("dplyr", "tibble"),
                          .combine = "rbind") %dopar% {
                                  print(i)
                                  
                                  var_input_full <- unlist(var_input_backup[i, ])
                                  
                                  App_func(
                                    imm_decay_corrected,
                                    var_input_full,
                                    fix_age_data_full,
                                    f_list,# initial state of female population
                                    m_list, # initial state of male population
                                    TimeStop_dynamics,# 1 year, weekly timestep for demographic component
                                    TimeStop_transmission, # 1 day, hourly timestep for transission component
                                    output,# model output: tracker or summary stats
                                    summary_df, #
                                    clean_environment,
                                    Vstart,
                                    Vprog,
                                    fixdata,
                                    vardata
                                  )
                                }
  
  ocOut.sum[[d]] <- Out.summary
  ocPars[[d]] <- var_input_backup
}

stopCluster(cl)

```


```{r analysisSummary}

################################
## POP & AGE-SEX SUMMARY ##
################################

# ocOut.summary is a dataframe of summary data for each parameter set 

## Plot population growth stats: 
# - Total Growth (20y), 
# - tenyr Growth (10y), 
# - Finyr Growth (1y)

summaryList <- ocOut.sum
ocOut.summary <- summaryList %>%
  do.call(rbind, .) %>%
  mutate(prof = rep(datasets, each = lhs_n), 
         set = rep(1:lhs_n, length(datasets))) %>% 
  replace(is.na(.), 0) %>%
  mutate(prof_group = ifelse(grepl("*shp*", prof), "shp", "goat"),
    prof = factor(
      prof,
      levels = c(
        "oc.goat.aridP",
        "oc.goat.semiaridP",
        "oc.goat.semiaridM",
        "oc.goat.subhumidM",
        "oc.goat.humidM",
        "oc.shp.aridP",
        "oc.shp.semiaridP",
        "oc.shp.semiaridM",
        "oc.shp.subhumidM",
        "oc.shp.humidM"
      )
    )
  )

ocParsls <- ocPars
ocPars.df <- ocParsls %>%
  do.call(rbind, .) %>%
  mutate(prof = rep(datasets, each = lhs_n), 
         set = rep(1:lhs_n, length(datasets))) %>% 
  replace(is.na(.), 0) %>%
  mutate(prof_group = ifelse(grepl("*shp*", prof), "shp", "goat"),
    prof = factor(
      prof,
      levels = c(
        "oc.goat.aridP",
        "oc.goat.semiaridP",
        "oc.goat.semiaridM",
        "oc.goat.subhumidM",
        "oc.goat.humidM",
        "oc.shp.aridP",
        "oc.shp.semiaridP",
        "oc.shp.semiaridM",
        "oc.shp.subhumidM",
        "oc.shp.humidM"
      )
    )
  )

# df of population growth stats:
popgrowth <- ocOut.summary %>% 
  select(prof, prof_group, ends_with("growth")) %>% 
  gather(key = "par", value = "prop", -c(prof,prof_group)) %>% 
  mutate(par = factor(par, levels = c("pop_growth",
                                      "tenyr_growth", 
                                      "twoyr_growth",
                                      "finyr_growth")))

growth_boxplot <- ggplot(popgrowth, aes(x=prof, y = prop, col = prof))+
  geom_boxplot(alpha = 0.5)+
  facet_wrap(~par, scales = "free", nrow = 1)+
  labs(x = "Growth Stat", 
       y = "Pop Growth",
       title = "Growth statistics for oc data, LHS parameter sets")+
  theme_bw()+
  scale_colour_manual(values = myPal)+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

growth_histGoat <- ggplot(popgrowth %>% filter(prof_group == "goat"), aes(prop))+
  geom_histogram()+
  facet_grid(prof~par, scales = "free")+
  labs(x = "Pop Growth", 
       y = "Count")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

growth_histShp <- ggplot(popgrowth %>% filter(prof_group == "shp"), aes(prop))+
  geom_histogram()+
  facet_grid(prof~par, scales = "free")+
  labs(x = "Pop Growth", 
       y = "Count")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

growth_hist <- ggplot(popgrowth, aes(prop))+
  geom_histogram()+
  facet_grid(prof~par, scales = "free")+
  labs(x = "Pop Growth", 
       y = "Count")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

growth_boxplot
growth_histGoat
growth_histShp
##
##

## Analyse age-sex dynamics:

# - Age-Sex plots
agesex <- ocOut.summary %>% 
  select(prof, prof_group, starts_with("pf"), starts_with("pm")) %>% 
  gather(key = "par", value = "prop", -c(prof,prof_group))

agesex_boxplot <- ggplot(agesex, aes(x=par, y = prop))+
  geom_boxplot(fill = "grey", 
               alpha = 0.5)+
  labs(x="Age-Sex Group", 
       y = "Proportion",
       title = "Stable Age-Sex structure, oc, (LHS parameter sets)")+
  theme_bw()+
  facet_wrap(~prof, ncol = 5)+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

agesex_boxplot2 <- ggplot(agesex, aes(x=prof, y = prop))+
  geom_boxplot(fill = "grey", 
               alpha = 0.5)+
  labs(x="Age-Sex Group", 
       y = "Proportion",
       title = "Stable Age-Sex structure, oc, (LHS parameter sets)")+
  theme_bw()+
  facet_wrap(~par, ncol = 4)+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
  
agesex_boxplot

summary_ShG <- ggarrange(growth_boxplot, agesex_boxplot, growth_histGoat, growth_histShp, nrow = 2, ncol = 2)
summary_ShG
filename_summary <- "summary_OCShG.png"

if(plotsave){
  ggsave(paste0("plots/",filename_summary), plot = summary_ShG, width = 40, height = 20, units = "cm")
}
```


```{r outValid}
#------------------------------------------------------------------------------
## VALID RESULTS ##

##################################
## Valid Age-Sex Conditions ##
##################################

## Min and max proportions for each sex-age group (see age-sex SS)
pfKid.min <- 0.05; pfKid.max <- 0.19
pfSub.min <- 0.06; pfSub.max <- 0.19
pfAdu.min <- 0.21; pfAdu.max <- 0.62

pmKid.min <- 0.05; pmKid.max <- 0.16
pmSub.min <- 0.04; pmSub.max <- 0.15
pmAdu.min <- 0.01; pmAdu.max <- 0.15
  

#########################################################
# Retain behavioral parameter sets
#########################################################

# Edit Out to contain identifier variables for pop growth (5%,15%) and pop growth with age-sex structure 
ocOut.growth <- ocOut.summary %>%
  mutate(tenyr_growth = replace_na(tenyr_growth, 0),
         # add variables to identify parameter sets with growth between 5% and 15%
         tenyr_15 = ifelse(tenyr_growth>=0.85 & tenyr_growth <=1.15, 1, 0),
         tenyr_05 = ifelse(tenyr_growth>=0.95 & tenyr_growth <=1.05, 1, 0)) %>%
  
  # add variables to identify parameter sets with growth between 5% and 15% AND age-sex conditions
  mutate(
    tenyr_15age = ifelse(
      tenyr_15 == 1 &
        pfKid >= pfKid.min & pfKid <= pfKid.max &
        pfSub >= pfSub.min & pfSub <= pfSub.max &
        pfAdu >= pfAdu.min & pfAdu <= pfAdu.max &
        
        pmKid >= pmKid.min & pmKid <= pmKid.max &
        pmSub >= pmSub.min & pmSub <= pmSub.max &
        pmAdu >= pmAdu.min & pmAdu <= pmAdu.max,1,0),
    
    tenyr_05age = ifelse(
      tenyr_05 == 1 &
        pfKid >= pfKid.min & pfKid <= pfKid.max &
        pfSub >= pfSub.min & pfSub <= pfSub.max &
        pfAdu >= pfAdu.min & pfAdu <= pfAdu.max &
        
        pmKid >= pmKid.min & pmKid <= pmKid.max &
        pmSub >= pmSub.min & pmSub <= pmSub.max &
        pmAdu >= pmAdu.min & pmAdu <= pmAdu.max,1,0)
  )

ocOut.growth %>% group_by(prof,tenyr_15age) %>% count() %>% kable()

# Growth easily within RSA conditions


# ##################
# ## Valid Output ##
# ##################

ocOut.valid <- ocOut.growth %>%
  filter(tenyr_15age == 1)

## Refine parameter dataframe:
ocPars.out <- ocPars.df %>%
  left_join(ocOut.growth %>%
              select(tenyr_growth, 
                     starts_with("imm"), 
                     prof, 
                     prof_group, 
                     set, 
                     tenyr_15age), 
            by = c("set", "prof", "prof_group"))

ocPars.valid <- ocPars.out %>%
  filter(tenyr_15age == 1, mortality_y>mortality_a)

pairs(ocPars.valid %>% select(NET_offtake_y:min_age_repro))

```


```{r validAgeSex}

ocOut.validLong <- ocOut.valid %>%
  select(prof, prof_group, starts_with("pf"), starts_with("pm")) %>% 
  gather(key = "par", value = "prop", -c(prof,prof_group))


stable_agesex <- ocOut.validLong %>% 
  group_by(prof, par) %>% 
  summarise(median = median(prop)) %>%
    pivot_wider(names_from = prof, values_from = median)
stable_agesex

agesex_filename <- "Applied_AgeSex_OC.csv"
# write.csv(stable_agesex, file = paste0("output/Applied/stableAgeSex/", agesex_filename), row.names = F)

# ahift to wide format

```


```{r validAnalysis}

ocPars.long <- ocPars.valid %>%
  select(-c(set, tenyr_15age)) %>%
  gather(key = "parameter", value = "par_val", -c(tenyr_growth, starts_with("imm"), prof, prof_group))


ggplot(ocPars.long, aes(x=par_val, y = tenyr_growth))+
  geom_point(aes(col = prof))+
  facet_wrap(~parameter, scales = "free")

ggplot(ocPars.long, aes(x=par_val, y = imm_V0))+
  geom_point(aes(col = prof))+
  facet_wrap(~parameter, scales = "free")

ggplot(ocPars.long, aes(x=par_val, y = imm_6m))+
  geom_point(aes(col = prof))+
  facet_wrap(~parameter, scales = "free")

ggplot(ocPars.long, aes(x=par_val, y = imm_12m))+
  geom_point(aes(col = prof))+
  facet_wrap(~parameter, scales = "free")
```




```{r validpars_analysis}
library(RColorBrewer)
# Load the Dark2 palette
dark2_palette <- c(brewer.pal(n = 8, name = "Dark2"), "#FF8C00", "#1E90FF", "#333333")

dark2_palette


validpars_GSA <- read_csv("data/GSA_parameters/GSA_valid-pars-only.csv", col_names = T)
validpars_RSA <- read_csv("data/GSA_parameters/GSA_var_input-PRCC.csv", col_names=T)

# Collate all valid parameters from GSA RSA
validPars_SA <- rbind(validpars_GSA, validpars_RSA) %>%
  # select pars to compare
  select(
    "off_mY",
    "off_mA",
    "off_f",      
    "mort_Y",     
    "mort_A",     
    "birth_rate", 
    # "max_yrs_F",  
    # "max_yrs_M",  
    "min_off",
    "min_repro",
  ) %>% 
  mutate(prof = "SA", prof_group = "SA")

validPars_oc <- ocPars.valid %>%
  select(
    "off_mY" = NET_offtake_m2,
    "off_mA" = NET_offtake_m,
    "off_f" = NET_offtake_f,     
    "mort_Y" = mortality_y,   
    "mort_A" = mortality_a,
    "birth_rate",
    # "max_yrs_F",  
    # "max_yrs_M",  
    "min_off" = min_age_offtake,
    "min_repro" = min_age_repro,
    prof,
    prof_group
  )

# join the RSA-GSA pars with the Applied pars:

validPars_df <- rbind(validPars_SA,
                      validPars_oc %>% select(colnames(validPars_SA))) %>% 
  as.data.frame()

# PAIRS PLOTS #

plot_pairsGt <- ggpairs(validPars_df %>% filter(prof_group != "shp"),
        columns = 1:8,
        legend = 1,
        aes(colour = prof,
            alpha = 0.5),
        upper = "blank", 
        progress = F)+
  scale_fill_manual(values = c(dark2_palette[1:5], "#333333"))+
  scale_colour_manual(values = c(dark2_palette[1:5], "#333333"))+
  theme(legend.position = "bottom")

plot_pairsSh <- ggpairs(validPars_df %>% filter(prof_group != "goat"),
        columns = 1:8,
        legend = 1,
        aes(colour = prof,
            alpha = 0.5),
        upper = "blank",
        progress = F)+
   scale_fill_manual(values = c(dark2_palette[6:10], "#333333"))+
  scale_colour_manual(values = c(dark2_palette[6:10], "#333333"))+
  theme(legend.position = "bottom")

plot_pairsGt
plot_pairsSh

######################################
## Vaccination Uncertainty Examples ##
######################################

validImm <- ocOut.valid %>%
  select(tenyr_growth, starts_with("imm"), prof, prof_group) %>%
  gather(key = "stat", value = "value", -c(prof,prof_group)) %>%
  mutate(stat = factor(stat, levels = c("imm_V0", "imm_6m", "imm_12m", "imm70_w", "tenyr_growth" )))

plot_imm <- ggplot(validImm %>% filter(stat %in% c("imm_V0", "imm_6m", "imm_12m")), 
       aes(x = prof, y = value, fill = stat))+ 
  geom_boxplot() +
  geom_hline(yintercept = 0.7, linetype = "dashed")+
  facet_wrap(~stat, scales = "free")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none")+
  scale_fill_manual(values = dark2_palette[1:3])

plot_imm70 <- ggplot(validImm %>% filter(stat %in% c("imm70_w")), 
            aes(x = prof, y = value, fill = stat))+ 
  geom_boxplot() +
  facet_wrap(~stat, scales = "free")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none")+
  scale_fill_manual(values = dark2_palette[4])


plot_tenyr <- ggplot(validImm %>% filter(stat %in% c("tenyr_growth")), 
                 aes(x = prof, y = as.numeric(value), fill = stat))+ 
  geom_boxplot() +
  facet_wrap(~stat, scales = "free")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "none")+
  scale_fill_manual(values = dark2_palette[5])

plot_ImmSum <- ggarrange(plot_imm,plot_imm70,plot_tenyr, ncol = 1)


filename_pairsSh <- "pairsvalid_SAOCShp.png"
filename_pairsGt <- "pairsvalid_SAOCGt.png"
filename_ImmSum <- "ImmSum100_OC.png"

if(plotsave){
  ggsave(paste0("plots/applied/",filename_pairsSh), plot = plot_pairsSh, width = 25, height = 20, units = "cm")
ggsave(paste0("plots/applied/",filename_pairsGt), plot = plot_pairsGt, width = 25, height = 20, units = "cm")
ggsave(paste0("plots/applied/",filename_ImmSum), plot = plot_ImmSum, width = 25, height = 20, units = "cm")
}

```