---
title: "oc_validation"
author: "Beth Savagar"
date: "2023-11-13"
output: html_document
---

# Global Sensitivity Analysis - LHS-PRCC

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Sensitivity Analysis
    i. Model Validation
    ii. LHS-PRCC

```{r loadLibraries, echo =F}
############
## SETUP ##
############
local <- T
filepath <- ""
filesave <- T # save files or no?

source(paste0(filepath,"scripts/setup.R")) # load libraries

custom_theme <- theme_bw() + theme(text = element_text(family = "Times New Roman", size = 11))
theme_set(custom_theme)
```

```{r sourceFunctions}
## Functions:
source(paste0(filepath, "functions/Appliedfunc.R")) # wrapper function
source(paste0(filepath, "functions/demos_summary.R")) # summary stats for output
source(paste0(filepath, "functions/dynmod-vac.R")) # flock dynamics model function
source(paste0(filepath, "functions/output.R")) # what to include in output df
source(paste0(filepath, "functions/GSA_outputs.R")) # summary stats accounting for vac
```

```{r loadData}
# load fixed pars: flock age-sex structure
fix_age_data_full <- read_csv("data/RSA_parameters/RSA_fix_input_final.csv",col_names=T)
# load variable demographic inputs: 
# original data for LHS:
var_demo_data_full <- read_csv("data/RSA_parameters/RSA_var_input_final.csv", col_names=T)
# valid data output from RSA (4140rows):
# var_demo_data_full <- read_csv("data/GSA_parameters/GSA_var_input-PRCC.csv", col_names=T)

imm_decay_corrected <- read_csv("data/imm_decay_bodjo_v2.csv") 

```

## Demographic Parameters Check:

```{r }

#######################
## Model Setup ##
#######################

TimeStop_dynamics <- 20*52 # Simulation Period (20yrs)
TimeStop_transmission <- 24 # 1 day, hourly timestep for transmission component
# turnover <- F; 
# transmission <- F; 
clean_environment <- T
applied_example <- F # remove if update app_func
min_pop <- 1 # set minimum size of population, if pop drops below then set to 0

# timepoints for population growth
t2 <- TimeStop_dynamics/2 # 10 yrs before end of simulation
t1 <- TimeStop_dynamics

output <- "dynamics" # define output type "summary" (age proporiotns), "summary_all" (age-sex proportions) or "count"
summary_df <- output_func(TimeStop_dynamics, output) # create summary data frame to store summary stats for each timestep


#######################
## Vaccination Setup ##
#######################
# For GSA only?
# Vaccination of 100% animals at mid-point of simulation.
Vstart <- TimeStop_dynamics/2 # 10 years, midpoint

Vprog <- data.frame(
  Vround = 1,
  Vtype = "full",
  Vweek = Vstart,
  Vmin = 0,
  Vmax = NA,
  pV = 1
)

Vstart <- Vprog %>% filter(Vround==1) %>% pull(Vweek)

#######################
## LHS Procedure ##
#######################
lhs <- T
lhs_n <- 2e5
pairs_plot <- F
SA <- TRUE
rates <- "yrly"

# Define range for each parameter: 
pars_min <- "min.final" # min val for LHS
pars_max <- "max.final" # max val for LHS
fixdata <- "sim.final" # colname for fixdata
vardata <- "sim.final" # colname for vardata

set.seed(1)
if(SA == TRUE){
  # latin hypercube sampling of parameter space:
  source("scripts/RSA/RSA_lhs2.R")
} 
## OUTPUT = var_input_set, lhs_n rows of sampled parameter sets. 

```

```{r savePars}

var_input_backup <- var_input_set %>% as.data.frame()

if(filesave){
  filename_parsAll <- paste0("GSA_parsAll_", Sys.Date(), ".csv")
  write_csv(var_input_backup, paste0(filepath, "output/GSA_output/", filename_parsAll)) # save paramter set
}

if(output == "dynamics"){
  var_input_backup <- var_input_set %>% as.data.frame() %>% slice_sample(.,n=100)
}

```

# Example of model dynamics output
```{r runModel_dynamics, eval = F}

## PARALLELISATION ##

cores=detectCores()
cl <- makeCluster(cores[1]-1) # for running locally
registerDoParallel(cl)

outDyn <- foreach (i = 1:nrow(var_input_backup),
                            .packages = c("dplyr", "tibble")) %dopar% {
                              print(i)
                              
                              var_input_full <- unlist(var_input_backup[i, ])
                              
                              App_func(
                                imm_decay_corrected,
                                var_input_full,
                                fix_age_data_full,
                                f_list,# initial state of female population
                                m_list, # initial state of male population
                                TimeStop_dynamics,# 1 year, weekly timestep for demographic component
                                TimeStop_transmission, # 1 day, hourly timestep for transission component
                                output,# model output: tracker or summary stats
                                summary_df, #
                                clean_environment,
                                Vstart,
                                Vprog,
                                fixdata,
                                vardata
                              )
                            }
stopCluster(cl)

```

```{r dynamicsAnalysis, eval = F}

popDyn <- lapply(outDyn, select, sum_pop) %>%
  bind_cols() %>%
  t() %>%
  as.data.frame()

colnames(popDyn) <- 1:ncol(popDyn)
rownames(popDyn) <- 1:nrow(popDyn)

popDyn.long <- popDyn %>%
  mutate(set = 1:nrow(.)) %>% 
  gather(key = "weeks", value = "sum_pop", -set) %>%
  mutate(weeks = as.numeric(weeks))

plot_popDyn <- ggplot(popDyn.long, aes(x = weeks, y = sum_pop, group = set)) +
  geom_line(col = "grey", alpha = 0.7)+
  labs(x="Time (weeks)", y = "Population Size")
plot_popDyn


```

# Update Model - Summary for Validation & PRCC:
```{r updateModel_summary, eval = F}
output <- "summary_all" # define output type "summary" (age proporiotns), "summary_all" (age-sex proportions) or "count"
summary_df <- output_func(TimeStop_dynamics, output) # create summary data frame to store summary stats for each timestep

# var_input_backup <- var_input_set %>% as.data.frame() %>% slice_sample(.,n=100)
# update parameter sets:
# var_input_backup <- read_csv("data/GSA_parameters/GSA_var_input-PRCC.csv") %>% rename(
#   "NET_offtake_m"= off_mA,
#   "NET_offtake_f"= off_f,
#   "mortality_y"= mort_Y,
#   "mortality_a"= mort_A,
#   "birth_rate"= birth_rate,
#   "adu_f_max_yrs"= max_yrs_F,
#   "adu_m_max_yrs"= max_yrs_M,
#   "min_age_offtake"= min_off,
#   "min_age_repro"= min_repro,
#   "NET_offtake_m2"=off_mY 
# ) %>%
#   as.data.frame()

```

# Run Model - Summary Stats:
```{r runModel_summary, eval = F}
## PARALLELISATION ##

cores=detectCores()
cl <- makeCluster(cores[1]-1) # for running locally
registerDoParallel(cl)

outGSA <- foreach (i = 1:nrow(var_input_backup),
                   .packages = c("dplyr", "tibble"),
                   .combine = "rbind"
                   ) %dopar% {
                              print(i)
                              
                              var_input_full <- unlist(var_input_backup[i, ])
                              
                              App_func(
                                imm_decay_corrected,
                                var_input_full,
                                fix_age_data_full,
                                f_list,# initial state of female population
                                m_list, # initial state of male population
                                TimeStop_dynamics,# 1 year, weekly timestep for demographic component
                                TimeStop_transmission, # 1 day, hourly timestep for transission component
                                output,# model output: tracker or summary stats
                                summary_df, #
                                clean_environment,
                                Vstart,
                                Vprog,
                                fixdata,
                                vardata
                              )
                            }
stopCluster(cl)
# saveRDS(outGSA, file = paste0("output/GSA_output/GSA_output_PRCC_", Sys.Date(), ".RData"))
```

# Preliminary analysis:
```{r summaryAnalysis1, eval = F}

# outGSA <- load(file = "output/GSA_output/GSA_output_PRCC_2023-12-16.RData")
# outGSA <- read_csv(file = "output/GSA_output/GSA_output_PRCC_2023-12-16.csv")
# var_input_backup <- read_csv(file = "output/GSA_output/GSA_parsAll_2023-12-16.csv")

# take a look at the data: 
str(outGSA)
str(var_input_set)
summary(var_input_set)

################
# Clean Data 
################

# add set id to output df:
outGSA <- outGSA %>%
  mutate(set = 1:nrow(outGSA))

# tidy parameters dataframe: 
parsGSA <- var_input_backup %>%
  select(NET_offtake_m, NET_offtake_m2, NET_offtake_f, everything()) %>%
  rename(off_mY = NET_offtake_m2,
         off_mA = NET_offtake_m,
         off_f = NET_offtake_f,
         mort_Y = mortality_y,
         mort_A = mortality_a,
         max_yrs_F = adu_f_max_yrs,
         max_yrs_M = adu_m_max_yrs,
         min_off = min_age_offtake,
         min_repro = min_age_repro
  ) %>%
  mutate(set = 1:nrow(var_input_backup))

#########################################################
# Analysis 1 - Identify behavioral parameter sets
#########################################################

# Growth & age-sex conditions: 
# +/-15% growth
growth_min <- 0.85
growth_max <- 1.15

## Min and max proportions for each sex-age group (see age-sex SS)
pfKid.min <- 0.05; pfKid.max <- 0.19
pfSub.min <- 0.06; pfSub.max <- 0.19
pfAdu.min <- 0.21; pfAdu.max <- 0.62

pmKid.min <- 0.05; pmKid.max <- 0.16
pmSub.min <- 0.04; pmSub.max <- 0.15
pmAdu.min <- 0.01; pmAdu.max <- 0.15

#####################################

outGSA.conditions <- outGSA %>%
  # growth condition
  mutate(tenyr_growth = replace_na(tenyr_growth, 0),
         tenyr_15 = ifelse(tenyr_growth>=growth_min & tenyr_growth <=growth_max, 1, 0)) %>%
  # agesex condition
    mutate(
    tenyr_15age = ifelse(
      tenyr_15 == 1 &
      pfKid >= pfKid.min & pfKid <= pfKid.max &
      pfSub >= pfSub.min & pfSub <= pfSub.max &
      pfAdu >= pfAdu.min & pfAdu <= pfAdu.max &
      
      pmKid >= pmKid.min & pmKid <= pmKid.max &
      pmSub >= pmSub.min & pmSub <= pmSub.max &
      pmAdu >= pmAdu.min & pmAdu <= pmAdu.max,1,0))

outGSA.valid <- outGSA.conditions %>%
  filter(tenyr_15age == 1)
# How many parameter sets are behavioural for growth of 5%, 15% and growth of 5%-15% with age-sex structure.

outGSA.conditions %>% group_by(tenyr_15) %>% count()
outGSA.conditions %>% group_by(tenyr_15age) %>% count()

parsGSA.conditions <- parsGSA %>%
  left_join(outGSA.conditions %>%
              select(tenyr_growth,
                     tenyr_15age,
                     set), by = c("set"))

parsGSA.valid <- parsGSA.conditions %>%
  filter(tenyr_15age == 1) %>%
  select(-c(tenyr_15age, set))

# pairs plot:

ggpairs(parsGSA.valid, 
        upper = list(continuous = wrap("cor", size = 7,family = "Times New Roman")),
        progress = F)

# save plot without tenyr growth: 
RSApairs <- ggpairs(parsGSA.valid %>% select(-tenyr_growth),
                    upper = list(continuous = wrap("cor", size = 4,family = "Times New Roman")),
                    progress = F)+theme(panel.grid.major = element_blank(), panel.grid.minor =element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"))
  
filename_RSApairs <- paste0("validpairs", ".png")

if(plotsave){
  ggsave(paste0("plots/",filename_RSApairs), plot = RSApairs, width = 20, height = 20, units = "cm")
}
```

# PRCC Analysis (Subset)

```{r prcc}

# Calculate PRCC for tenyr_growth and immunity metrics, on valid parameters:
prccGSA.valid <- parsGSA.valid %>%
  # add immunity dynamics:
  bind_cols(outGSA.valid %>% select(imm_6m,imm_12m,imm70_w)) 

# RENAME FROM HERE
prccb_imm6m <- epi.prcc(prccGSA.valid %>% select(-c("tenyr_growth", "imm_12m","imm70_w")), 
                        sided.test = 2, conf.level = 0.95)

prccb_imm12m <- epi.prcc(prccGSA.valid %>% select(-c("tenyr_growth","imm_6m","imm70_w")), 
                         sided.test = 2, conf.level = 0.95)

prccb_imm70 <- epi.prcc(prccGSA.valid %>% select(-c("tenyr_growth","imm_6m","imm_12m")), 
                        sided.test = 2, conf.level = 0.95)

prccb_growth <- epi.prcc(prccGSA.valid %>% select(-c("imm_6m","imm_12m","imm70_w")), 
                         sided.test = 2, conf.level = 0.95)
```


```{r prccAnalysis}

# Bar plot comparing prcc for each output
prccb.all <- rbind(prccb_imm6m %>% select(var,est) %>% mutate(output = "imm6m"),
                  prccb_imm12m %>% select(var,est) %>% mutate(output = "imm12m"),
                  prccb_imm70 %>% select(var,est) %>% mutate(output = "imm70"), 
                  prccb_growth %>% select(var,est) %>% mutate(output = "pop_growth"))

prcc_summary <- 
  prccb_imm70 %>% 
          select(var,est,p.value) %>% 
          transmute(var = var,
                    est70=round(est,digits=3),
                    p70= round(p.value, digits=3)) %>%
  cbind(prccb_imm6m %>% 
  select(var,est,p.value) %>% 
  transmute(est6m=round(est,digits=3),
            p6m= round(p.value, digits=3))) %>%
  cbind(prccb_imm12m %>% 
          select(var,est,p.value) %>% 
          transmute(est12m=round(est,digits=3),
                    p12m= round(p.value, digits=3))) %>%
  arrange(desc(abs(est70)))

prcc_summary

varOrder <- prcc_summary %>% select(var) %>% pull()
# varOrder <- c("off_f", "off_mY", "off_mA", "mort_Y", "mort_A", "birth_rate", "min_off", "min_repro", "max_yrs_F","max_yrs_M")

GSAsubset_prccimmunity <- ggplot(prccb.all %>% mutate(var = factor(var, levels = rev(varOrder))) %>% filter(!output == "pop_growth"), 
       aes(x=est, y=var, group = output, fill = output))+
  geom_col(position = "dodge")+
  labs(x="PRCC", y="Demographic Parameter", fill = "Output", title = "")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  scale_fill_grey()
GSAsubset_prccimmunity

GSAsubset_prccgrowth <- ggplot(prccb.all %>% mutate(var = factor(var, levels = rev(varOrder))) %>% filter(output == "pop_growth"), 
       aes(x=est, y=var, group = output, fill = output))+
  geom_col(position = "dodge")+
  labs(x="PRCC", y="Demographic Parameter", fill = "Output", title = "")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  scale_fill_grey()
GSAsubset_prccgrowth

GSAsubset_prccall <- ggplot(prccb.all %>% mutate(var = factor(var, levels = rev(varOrder))), 
       aes(x=est, y=var, group = output, fill = output))+
  geom_col(position = "dodge")+
  labs(x="PRCC", y="Demographic Parameter", fill = "Output", title = "")+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  scale_fill_grey()
GSAsubset_prccall

filename_GSAsubset_prccimmunity <- "GSAsubset_prccimmunity.png"
filename_GSAsubset_prccgrowth <- "GSAsubset_prccgrowth.png"
filename_GSAsubset_prccall <- "GSAsubset_prccall.png"

if(plotsave){
  ggsave(paste0("plots/GSA/",filename_GSAsubset_prccimmunity), plot = GSAsubset_prccimmunity, width = 15, height = 15, units = "cm")
  ggsave(paste0("plots/GSA/",filename_GSAsubset_prccgrowth), plot = GSAsubset_prccgrowth, width = 15, height = 15, units = "cm")
  ggsave(paste0("plots/GSA/",filename_GSAsubset_prccall), plot = GSAsubset_prccall, width = 12, height = 7.5, units = "cm")
  write_csv(prcc_summary, paste("tables/GSAvalid_prccimmunity.csv"))
}

```


```{r PRCCall}
##############################
## PRCC GSA - with All pars ##
##############################
# 
prccGSA <- parsGSA %>%
  select(-set) %>%
  bind_cols(outGSA %>% select(tenyr_growth))

prccb_growthAll <- epi.prcc(prccGSA, sided.test = 2, conf.level = 0.95)

prcc_growth <- prccb_growthAll %>%
  select(var, est, p.value) %>%
  transmute(
    var = var,
    growth = round(est, digits = 3),
    pgrowth = round(p.value, digits = 3)
  ) %>%
  arrange(desc(abs(growth)))

growthOrder <- prcc_growth %>% select(var) %>% pull()

GSAall_prccgrowth <- ggplot(prcc_growth %>% mutate(var = factor(var, levels = rev(varOrder))), # growthOrder
      aes(x=growth, y=var))+
    geom_col()+
    labs(x="PRCC", y="Demographic Parameter", title = "All Sets, tenyr_growth")+
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
    scale_fill_grey()
GSAall_prccgrowth

filename_GSAall_prccgrowth <- "GSAall_prccgrowth.png"

if(plotsave) {
  ggsave(
    paste0("plots/GSA/", filename_GSAall_prccgrowth),
    plot = GSAall_prccgrowth,
    width = 7.5,
    height = 7.5,
    units = "cm"
  )
  write_csv(prcc_growth, "tables/GSAall_prccgrowth.csv")
}
     
```