---
title: "Lesnoff_validation"
author: "Beth Savagar"
date: "2023-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}

applied_example <- F
local <- T

############
## SETUP ##
############

# local filepath: 
if(local){
  filepath <- ""
}else{
  # cluster filepath
  filepath <- "/storage/users/bsavagar/"
}

## Libraries
source(paste0(filepath,"scripts/setup.R")) 

## Functions:
source(paste0(filepath, "functions/Appliedfunc.R")) # wrapper function
source(paste0(filepath, "functions/demos_summary.R")) # summary stats for output
source(paste0(filepath, "functions/dynmod-vac.R")) # flock dynamics model function
source(paste0(filepath, "functions/output.R")) # what to include in output df
source(paste0(filepath, "functions/GSA_outputs.R")) # summary stats accounting for vac
```


```{r loadpars}
## Load parameters
datafile <- "-lesnoff_validation"
source(paste0(filepath, "scripts/applied/applied_load_data2.R")) 

## Datasets
datasets <- fix_age_data_full %>% select(-c(parameter)) %>% colnames()
```

```{r modsetup}
######################
## MODEL SETUP ##
######################

## Simulation:
TimeStop_dynamics <- 10*52 # 2 years only interested in rates for 1 y
TimeStop_transmission <- 24 # 1 day, hourly timestep for transmission component
min_pop <- 1 # set minimum size of population, if pop drops below then set to 0

## Model Output
output <- "dynamics" # Output options: "summary" (stats with age-group prop), "summary_all" (stats with age-sex group prop), "dynamics" (pop metrics over time)

#######################
## Vaccination Setup ##
#######################
# see applied_vaccination
pV <- 1
source("scripts/applied/applied_vaccination.R")
Vstart <- Vprog %>% filter(Vround==1) %>% pull(Vweek)

##################
## MODEL INPUTS ##
##################

# create empty dataframe to store output
summary_df <- output_func(TimeStop_dynamics, output) 

turnover <- F; 
dynamics <- T; 
transmission <- F; 
clean_environment <- T

# timepoints for population growth
t2 <- TimeStop_dynamics/2 # 5 year pop growth
t1 <- TimeStop_dynamics


```


```{r lesnoffMod}

##################################
## LHS DEMOGRAPHIC PARS ##
##################################

dataset <- "lesnoff.yr" # for selecting state_vars input data
data_filename <- gsub("\\.","",dataset)

lhs <- T

if(dataset == "lesnoff.ft"){
  rates <- "wkly"
}else{
  rates <- "yrly"
}

var_input_lesnoffv2 <- read_csv("data/Applied_parameters/demographics-lesnoff_input2.csv")

# Format demographic parameter sets:
var_input_backup <- var_input_lesnoffv2 %>% as.data.frame()

Out_lesnoff2 <- c()


#####################
## PARALLELISATION ##
#####################

print("start-parallel")

## Local parallelisation
if(local){
  cores=detectCores()
  cl <- makeCluster(cores[1]-1)
  registerDoParallel(cl)
}else{
  cores=detectCores()
  cl <- makeCluster(10)
  registerDoParallel(cl)
}
print("parallel-verified")
print("start-model")


################
## SIMULATION ##
################
Out_lesnoff2 <- foreach (i = 1:nrow(var_input_backup), 
                .packages = c("dplyr", "tibble")
) %dopar% {
  
  print(i)
  var_input_full <- unlist(var_input_backup[i,])
  
  App_func(
    imm_decay_corrected,
    var_input_full,
    fix_age_data_full,
    f_list, # initial state of female population
    m_list, # initial state of male population
    TimeStop_dynamics, # 1 year, weekly timestep for demographic component
    TimeStop_transmission, # 1 day, hourly timestep for transission component
    output, # model output: tracker or summary stats
    summary_df, #
    clean_environment,
    Vstart,
    Vprog,
    fixdata,
    vardata
  )
}

stopCluster(cl)

```

```{r lesnoffGrowth}

## CHECK VACCINATION ##

# Check that vaccination is implemented correctly:
ggplot(testDyn, aes(x=w,y=prop_immune))+geom_point()
```
```{r modsetup2}
######################
## MODEL SETUP ##
######################

## Simulation:
TimeStop_dynamics <- 10*52 # 2 years only interested in rates for 1 y
TimeStop_transmission <- 24 # 1 day, hourly timestep for transmission component
min_pop <- 1 # set minimum size of population, if pop drops below then set to 0

## Model Output
output <- "summary_all" # Output options: "summary" (stats with age-group prop), "summary_all" (stats with age-sex group prop), "dynamics" (pop metrics over time)

#######################
## Vaccination Setup ##
#######################
# see applied_vaccination
pV <- 1
source("scripts/applied/applied_vaccination.R")
Vstart <- Vprog %>% filter(Vround==1) %>% pull(Vweek)

##################
## MODEL INPUTS ##
##################

# create empty dataframe to store output
summary_df <- output_func(TimeStop_dynamics, output) 

turnover <- F; 
dynamics <- T; 
transmission <- F; 
clean_environment <- T

# timepoints for population growth
t2 <- TimeStop_dynamics/2 # 5 year pop growth
t1 <- TimeStop_dynamics


```


```{r lesnoffMod2}

##################################
## LHS DEMOGRAPHIC PARS ##
##################################

dataset <- "lesnoff.yr" # for selecting state_vars input data
data_filename <- gsub("\\.","",dataset)

lhs <- T

if(dataset == "lesnoff.ft"){
  rates <- "wkly"
}else{
  rates <- "yrly"
}

var_input_lesnoffv2 <- read_csv("data/Applied_parameters/demographics-lesnoff_input2.csv")

# Format demographic parameter sets:
var_input_backup <- var_input_lesnoffv2 %>% as.data.frame()

Out_lesnoff2 <- c()


#####################
## PARALLELISATION ##
#####################

print("start-parallel")

## Local parallelisation
if(local){
  cores=detectCores()
  cl <- makeCluster(cores[1]-1)
  registerDoParallel(cl)
}else{
  cores=detectCores()
  cl <- makeCluster(10)
  registerDoParallel(cl)
}
print("parallel-verified")
print("start-model")


################
## SIMULATION ##
################
Out_lesnoff2 <- foreach (i = 1:nrow(var_input_backup), 
                .packages = c("dplyr", "tibble"),
                .combine = "rbind"
) %dopar% {
  
  print(i)
  var_input_full <- unlist(var_input_backup[i,])
  
  App_func(
    imm_decay_corrected,
    var_input_full,
    fix_age_data_full,
    f_list, # initial state of female population
    m_list, # initial state of male population
    TimeStop_dynamics, # 1 year, weekly timestep for demographic component
    TimeStop_transmission, # 1 day, hourly timestep for transission component
    output, # model output: tracker or summary stats
    summary_df, #
    clean_environment,
    Vstart,
    Vprog,
    fixdata,
    vardata
  )
}

stopCluster(cl)

```


```{r immMetrics}

# df of population growth stats:
immSumm <- Out_lesnoff2 %>% 
  select(starts_with("imm")) %>% 
  gather(key = "par", value = "prop")

ggplot(immSumm %>% filter(!par == "imm70_w"), aes(x=par, y = prop))+
  geom_boxplot()+
  labs(x = "Imm Stat", 
       y = "Prop Immune",
       title = "Imm statistics for Lesnoff data, valid")+
  theme_bw()
growth_summplot


Out_lesnoff2 %>% select(starts_with("imm")) %>% summary()




```
