---
title: "Regional Sensitivity Analysis"
author: "Beth Savagar"
date: "2023-04-26"
output: pdf_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup,include=FALSE}
# -----------------------
## SETUP ##
# Load libraries, functions etc
library(tidyverse)
library(readr)
library(here)
library(ggpubr)
library(knitr)
here()
source("functions/demos_summary.R")
source("functions/output.R")
source("functions/dynmod.R")

```

```{r loaddata}

fix_age_data_full <- read_csv("data/RSA_parameters/RSA_fix_input.csv",col_names=T)
var_demo_data_full <- read_csv("data/RSA_parameters/RSA_var_input.csv", col_names=T)
imm_decay_corrected <- read_csv("data/imm_decay_bodjo_v2.csv") # "scripts/demographic-data/mat-imm-decay.R" for workings
```

Run the Regional Sensitivity Analysis for 25 years over 10000 lhs parameter sets. 
- NB: Run with broad prior parameters, RSA_var_input - min.3, max.3 on 20/06/2023 - this is example 4 on the presentation and links with the relaxed conditions in RSA_analysis_2 with adult_male proportion = 20%

```{r model-setup}

# -----------------------
## MODEL PARAMETERS ##

TimeStop_dynamics <- 25*52 # 10 years
TimeStop_transmission <- 24 # 1 day, hourly timestep for transmission component
output <- "summary_all" # define output type "summary" (age proporiotns), "summary_all" (age-sex proportions) or "count"
min_pop <- 1 # set minimum size of population, if pop drops below then set to 0
pars_filename <- "set_pars_RSA.R"
lhs_n <- 1e4

# ---------------------------------
## SENSITIVITY ANALYSIS PARAMETERS:

SA <- TRUE
set.seed(1)
if(SA == TRUE){
  # select parameter min-max pair (see RSA_var_input.csv)
pars_min <- "min.1"
pars_max <- "max.1"

# latin hypercube sampling of parameter space:
# output is var_input_set dataframe with sampled parameter sets for each variable input (demographic) parameter
source("scripts/RSA/RSA_lhs.R")
}else{
# test_1 dataset, all aprameters set to 0 and all animals in age group 1 (susceptible)
dataset1 <- "sim.1" # select dataset for test data
dataset2 <- "sim.1" # select dataset for age data
}

```

```{r modelrun}


## RSA FOR-LOOP
RSAoutput <- c()

# timepoints for the population growth
t2 <- 15*52
t1 <- TimeStop_dynamics

for(i in 1:lhs_n){
  # print(i)
  source("scripts/parameters/set-pars-RSA.R")
  # output is demographic pars dataframe (for sex-age-groupings) and starting population m_list, f_list
  
  
  # ---------------------------------
  ## TRANSMISSION PARAMETERS:
  transmission <- F # include transmission? T = Yes, F = No
  
  # transmission_pars <- "fixed"
  # transmission_filepath <- paste0("scripts/parameters/set-pars-transmission-",transmission_pars,".R")
  # source(transmission_filepath)
  source(here("scripts", "parameters", "set-pars-transmission-fixed.R"))
  #print(c(i,off_F ,off_M ,mort_1,mort_2,birth_r))
  
  ## Clean Parameters Environment? ##
  clean_environment <- T
  if (clean_environment == T) {
    rm(var_demo_data,fix_age_data,kid_f_prop,sub_f_prop,adu_f_prop,kid_m_prop,sub_m_prop,adu_m_prop,kid_max,sub_max, max_age_F,max_age_M,fIm_init,fS_init,fE_init,fI_init,fR_init,mIm_init,mS_init,mE_init,mI_init,mR_init,off_1,off_F,off_M,mort_1,mort_2,birth_r,ppr_mort_1,ppr_mort_2)
    }
  
  # -----------------------
  ## SUMMARY STATS ##
  
  # create summary data frame to store summary stats for each timestep
  summary_df <- output_func(TimeStop_dynamics, output)
  
  # nb need to add if statement to summary (if output == summary, if output == counts)
  summary_df <- summary_demos(w = 1, f_list, m_list, output, summary_df)
  
  output_df <- dynmod_func(
    f_list,# initial state of female population
    m_list,# initial state of male population
    TimeStop_dynamics,# 1 year, weekly timestep for demographic component
    TimeStop_transmission,# 1 day, hourly timestep for transission component
    output,# model output: tracker or summary stats
    demographic_pars,
    summary_df
  )

  output_df <- output_df %>% replace(is.na(.), 0)
 
  
  ## output is pop growth from t=0 to end
  
  res <- output_df %>%
   filter(w==TimeStop_dynamics) %>%
   mutate(pop_growth = output_df[nrow(output_df),"sum_pop"] / output_df[1,"sum_pop"],
          tenyr_growth = output_df[t2, "sum_pop"] / output_df[t1, "sum_pop"],
          set = i)
  
  RSAoutput <- RSAoutput %>%
    rbind(res)
}

# write.csv(RSAoutput,"output/RSA_output/RSAoutput_20230601.csv",row.names=F)
# write.csv(var_input_set,"output/RSA_output/var-input-set_20230601.csv",row.names=F)


```


```{r pairs}

validRSA <-  RSAoutput %>%
  filter(pop_growth != 0)


ggplot(validRSA, aes(x=set, y=sum_pop))+geom_point()+coord_cartesian(y=c(0,250))
ggplot(validRSA, aes(x=set, y=pop_growth))+geom_point()+coord_cartesian(y=c(0,2.5))

validRSA2 <- validRSA %>%
  filter(pop_growth>=0.95, pop_growth <=1.05)


valid_pars <- RSAoutput %>%
  filter(pop_growth != 0) %>%
  pull(set)


valid_pars2 <- validRSA2 %>%
  pull(set)

valid_pars_df <- var_input_set[valid_pars,]
valid_pars_df2 <-  var_input_set[valid_pars2,]

pairs(valid_pars_df)
pairs(valid_pars_df2)
```


```{r validpars_pop}

validpops <- validRSA2 %>% 
  select(starts_with("pf")|starts_with("pm")|starts_with(("pF"))) %>%
  gather(key=stat, value=prop) %>%
  mutate(sex = ifelse(stat %in% c("pmKid","pmSub","pmAdu"), "M", "F"))

ggplot(validpops, aes(x=stat, y=prop, col = sex))+geom_boxplot()



```
```{r popdynamics, echo = F}

set <- validRSA2 %>% pull(set)
validpop <- c()
for(i in set){
  source("scripts/parameters/set-pars-RSA.R")
  # output is demographic pars dataframe (for sex-age-groupings) and starting population m_list, f_list
  
  
  # ---------------------------------
  ## TRANSMISSION PARAMETERS:
  transmission <- F # include transmission? T = Yes, F = No
  
  # transmission_pars <- "fixed"
  # transmission_filepath <- paste0("scripts/parameters/set-pars-transmission-",transmission_pars,".R")
  # source(transmission_filepath)
  source(here("scripts", "parameters", "set-pars-transmission-fixed.R"))
  #print(c(i,off_F ,off_M ,mort_1,mort_2,birth_r))
  
  ## Clean Parameters Environment? ##
  clean_environment <- T
  if (clean_environment == T) {
    rm(var_demo_data,fix_age_data,kid_f_prop,sub_f_prop,adu_f_prop,kid_m_prop,sub_m_prop,adu_m_prop,kid_max,sub_max, max_age_F,max_age_M,fIm_init,fS_init,fE_init,fI_init,fR_init,mIm_init,mS_init,mE_init,mI_init,mR_init,off_1,off_F,off_M,mort_1,mort_2,birth_r,ppr_mort_1,ppr_mort_2)
  }
  
  # -----------------------
  ## SUMMARY STATS ##
  
  # create summary data frame to store summary stats for each timestep
  summary_df <- output_func(TimeStop_dynamics, output)
  
  # nb need to add if statement to summary (if output == summary, if output == counts)
  summary_df <- summary_demos(w = 1, f_list, m_list, output, summary_df)
  
  output_df <- dynmod_func(
    f_list,# initial state of female population
    m_list,# initial state of male population
    TimeStop_dynamics,# 1 year, weekly timestep for demographic component
    TimeStop_transmission,# 1 day, hourly timestep for transission component
    output,# model output: tracker or summary stats
    demographic_pars,
    summary_df
  )
  
  output_df <- output_df %>% replace(is.na(.), 0)
  
  res <- output_df %>%
    pull(sum_pop)
  plot(res)

  validpop <- validpop %>%
    rbind(res)

}

validpop_long <- validpop %>% 
  as.data.frame() %>%
  #rename_with(as.character(seq(1,520,1)), everything())
  mutate(set = set) %>% 
  gather(key="w", value = "pop", -set) %>%
  mutate(w = str_remove(w,"V"), 
         w = as.numeric(w))

ggplot(validpop_long, aes(x=w, y=pop, col = set))+geom_line()


```